### ISSUE TITLE
[BUG] Internal CE error with anonymous inner structs on Wine MSVC

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#2093]
**Describe the bug**
Giving Wine MSVC an anonymous inner struct with an initializer somehow makes CE emit
```
Internal Compiler Explorer error: TypeError: Cannot read property 'localeCompare' of undefined
    at /infra/.deploy/lib/asm-parser-vc.js:296:36
    at Array.sort (<anonymous>)
    at AsmParser.resultObjectIntoArray (/infra/.deploy/lib/asm-parser-vc.js:273:23)
    at AsmParser.processAsm (/infra/.deploy/lib/asm-parser-vc.js:269:21)
    at AsmParser.process (/infra/.deploy/lib/asm-parser.js:571:21)
    at WineVcCompiler.processAsm (/infra/.deploy/lib/base-compiler.js:863:25)
    at /infra/.deploy/lib/base-compiler.js:831:38
    at async run (/infra/.deploy/node_modules/p-queue/dist/index.js:255:29)
```

This is a corner case that needs four different rare options simultaneously, so it's fine if this is deprioritized or wontfix.

**To Reproduce**
```
struct a {
    struct { int b = 123; } c;
};

void d()
{
    a e;
}
```
Reproduces on all Wine MSVC versions, including non-x86. Does not reproduce on GCC, Clang, or x64 MSVC (though x64 MSVC demangles it incorrectly - possibly the same bug?).

**Expected behavior**
Not an ICEE.

**Link**
https://godbolt.org/z/e649Gd

**Comment by mattgodbolt** [comment]
Wow, this is an interesting one: thanks for filing!

**Comment by partouf** [comment]
Fix is now live
