### ISSUE TITLE
[BUG] Non-working Kotlin compilers

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2698]
Kotlin compilers working:

- 1.4.0
- 1.4.10
- 1.5.0

Not working:

- 1.4.20
- 1.4.21
- 1.4.30
- 1.4.31
- 1.4.32

Ideas?

_Originally posted by @partouf in https://github.com/compiler-explorer/compiler-explorer/issues/2637#issuecomment-853417905_

**Comment by partouf** [comment]
Original config:

```
group.kotlin.compilers=kotlinc1400:kotlinc1410:kotlinc1420:kotlinc1421:kotlinc1430:kotlinc1431:kotlinc1432:kotlinc1500
compiler.kotlinc1400.exe=/opt/compiler-explorer/kotlin-jvm-1.4.0/bin/kotlinc-jvm
compiler.kotlinc1400.name=kotlinc 1.4.0
compiler.kotlinc1400.java_home=/opt/compiler-explorer/jdk-16.0.1
compiler.kotlinc1410.exe=/opt/compiler-explorer/kotlin-jvm-1.4.10/bin/kotlinc-jvm
compiler.kotlinc1410.name=kotlinc 1.4.10
compiler.kotlinc1410.java_home=/opt/compiler-explorer/jdk-16.0.1
compiler.kotlinc1420.exe=/opt/compiler-explorer/kotlin-jvm-1.4.20/bin/kotlinc-jvm
compiler.kotlinc1420.name=kotlinc 1.4.20
compiler.kotlinc1420.java_home=/opt/compiler-explorer/jdk-16.0.1
compiler.kotlinc1421.exe=/opt/compiler-explorer/kotlin-jvm-1.4.21/bin/kotlinc-jvm
compiler.kotlinc1421.name=kotlinc 1.4.21
compiler.kotlinc1421.java_home=/opt/compiler-explorer/jdk-16.0.1
compiler.kotlinc1430.exe=/opt/compiler-explorer/kotlin-jvm-1.4.30/bin/kotlinc-jvm
compiler.kotlinc1430.name=kotlinc 1.4.30
compiler.kotlinc1430.java_home=/opt/compiler-explorer/jdk-16.0.1
compiler.kotlinc1431.exe=/opt/compiler-explorer/kotlin-jvm-1.4.31/bin/kotlinc-jvm
compiler.kotlinc1431.name=kotlinc 1.4.31
compiler.kotlinc1431.java_home=/opt/compiler-explorer/jdk-16.0.1
compiler.kotlinc1432.exe=/opt/compiler-explorer/kotlin-jvm-1.4.32/bin/kotlinc-jvm
compiler.kotlinc1432.name=kotlinc 1.4.32
compiler.kotlinc1432.java_home=/opt/compiler-explorer/jdk-16.0.1
compiler.kotlinc1500.exe=/opt/compiler-explorer/kotlin-jvm-1.5.0/bin/kotlinc-jvm
compiler.kotlinc1500.name=kotlinc 1.5.0
compiler.kotlinc1500.java_home=/opt/compiler-explorer/jdk-16.0.1
```

**Comment by partouf** [comment]
Error for just the default example on one of the non-working compilers, other non-working compilers give same error:

```
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
exception: java.lang.ExceptionInInitializerError
	at com.intellij.pom.java.LanguageLevel.<clinit>(LanguageLevel.java:25)
	at com.intellij.core.CoreLanguageLevelProjectExtension.<init>(CoreLanguageLevelProjectExtension.java:26)
	at com.intellij.core.JavaCoreProjectEnvironment.<init>(JavaCoreProjectEnvironment.java:42)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreProjectEnvironment.<init>(KotlinCoreProjectEnvironment.kt:26)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.<init>(KotlinCoreEnvironment.kt:118)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:420)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:226)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:152)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:76)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:45)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:227)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit$default(CLITool.kt:225)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:214)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler$Companion.main(K2JVMCompiler.kt:271)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.main(K2JVMCompiler.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.jetbrains.kotlin.preloading.Preloader.run(Preloader.java:87)
	at org.jetbrains.kotlin.preloading.Preloader.main(Preloader.java:44)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.util.ResourceBundle.setParent(java.util.ResourceBundle) accessible: module java.base does not "opens java.util" to unnamed module @2bea5ab4
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.intellij.util.ReflectionUtil.makeAccessible(ReflectionUtil.java:252)
	at com.intellij.util.ReflectionUtil.getDeclaredMethod(ReflectionUtil.java:269)
	at com.intellij.DynamicBundle.<clinit>(DynamicBundle.java:22)
	... 25 more

Compiler returned: 2
```

**Comment by DanielBelow** [comment]
I looked into that a little bit: 

There's a comment for that in the kotlinc script [here](https://github.com/JetBrains/kotlin/blob/92d200e093c693b3c06e53a39e0b0973b84c7ec5/compiler/cli/bin/kotlinc#L76) linking to [IDEA-248785](https://youtrack.jetbrains.com/issue/IDEA-248785).

There's a comment explaining
>  JDK internals are now encapsulated by default in JDK 16 since this commit in OpenJDK (affects jdk-16+28 and later), which means that the Kotlin compiler doesn't work out of the box on JDK 16 builds.

Not sure why 1.4.0 works, as the fix/workaround in the kotlinc script doesn't seem to be on the [1.4.0 branch](https://github.com/JetBrains/kotlin/blob/1.4.0/compiler/cli/bin/kotlinc)... 

Maybe it's easiest to use JDK 11 as JAVA_HOME instead of 16 (?)

**Comment by partouf** [comment]
Some testing for both javac and javap would be appreciated, for now I'm leaving the non-working compilers out

**Comment by partouf** [comment]
Just to be on the safe side, ill disable 1.4 for now as well

**Comment by DanielBelow** [comment]
I was able to test locally with 

JDKs
- corretto-11.0.10
- corretto-15.0.2
- openjdk-16.0.1

kotlinc versions
- 1.4.0
- 1.4.10
- 1.4.20
- 1.4.21
- 1.4.30
- 1.4.31
- 1.4.32
- 1.5.0

I tried to compile a simple Hello-World with all combinations of JDKs x kotlinc versions.

The combinations where I see the exception

```
exception: java.lang.ExceptionInInitializerError
  at com.intellij.pom.java.LanguageLevel.<clinit>(LanguageLevel.java:25)
  at com.intellij.core.CoreLanguageLevelProjectExtension.<init>(CoreLanguageLevelProjectExtension.java:26)
  at com.intellij.core.JavaCoreProjectEnvironment.<init>(JavaCoreProjectEnvironment.java:42)
[...]
```

are 1.4.20, 1.4.21, 1.4.30, 1.4.31 and 1.4.32 with openjdk-16. The others show no errors.

Checking `javap` I excluded openjdk-16, and didn't see any errors for class files generated by any of the kotlinc versions.

**Comment by supergrecko** [comment]
I've tested non-working Kotlin compilers against older open-jdk versions (11, 13, 14 & 15) and they seem to work fine.

Because Java class files are backwards compatible the newer versions of javap should always be able to deal with older class files. I believe using the latest (openjdk-16/javap) javap shouldn't cause any problems.

Until the Kotlin folks backport the ExceptionInInitializer failure to the older compilers I suggest we use an older jdk version. Older openjdk versions are already on infra.

**Comment by DanielBelow** [comment]
There still seem to be some issues for these compilers:(

> /opt/compiler-explorer/kotlin-jvm-1.4.30/bin/kotlinc: line 80: java: command not found

Affects all, but 1.5.0 and 1.5.10. 
I suppose it's all kotlin compilers using JDK 15.0.1. Looking at Java, there's only an option for 15.0.2, not 15.0.1. Maybe a typo?

**Comment by supergrecko** [comment]
> There still seem to be some issues for these compilers:(
> 
> > /opt/compiler-explorer/kotlin-jvm-1.4.30/bin/kotlinc: line 80: java: command not found
> 
> Affects all, but 1.5.0 and 1.5.10.
> I suppose it's all kotlin compilers using JDK 15.0.1. Looking at Java, there's only an option for 15.0.2, not 15.0.1. Maybe a typo?

It seems like you're right. I suppose it defaulted to my default JDK, therefore testing passed on my machine when I tested. Would be great if you (or anyone else interested) could submit a fix, I can take a closer look later this week if you are busy.
