### ISSUE TITLE
[BUG] make error

### ISSUE THREAD

**Issue by videcode** [compiler-explorer/compiler-explorer#2915]
run in console: make

...
./node_modules/webpack-cli/bin/cli.js "-p"
Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, filter?, transformAll?, toType?, force?, priority?, info?, transform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
/home/user/Documents/programs/compiler-explorer/node_modules/copy-webpack-plugin/node_modules/schema-utils/dist/validate.js:1
ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, filter?, transformAll?, toType?, force?, priority?, info?, transform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
    at validate (/home/user/Documents/programs/compiler-explorer/node_modules/copy-webpack-plugin/node_modules/schema-utils/dist/validate.js:105:11)
    at new CopyPlugin (/home/user/Documents/programs/compiler-explorer/node_modules/copy-webpack-plugin/dist/index.js:38:31)
    at Object.<anonymous> (/home/user/Documents/programs/compiler-explorer/webpack.config.esm.js:52:5)
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (/home/user/Documents/programs/compiler-explorer/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
make: *** [Makefile:58: webpack] Error 1

**Comment by saurabhjimmy** [comment]
Revert your node to v12.22.5 lts/erbium. It should work. More on the error - 

I think it's not exactly an error with webpack packages but with the 'copywebpack' plugin itself, which manifests into files not being copied correctly and make failing.

With the update to the 6.x major version came a breaking change: instead of just passing the array with the config patterns directly to the CopyWebpackPlugin constructor, your now have to wrap it in the patterns property of an object and pass that.

Old syntax:

new CopyWebpackPlugin(
  [
    { from: 'src/xxx.ext', to: 'dist/xxx.ext' },
    { from: 'src/yyy.ext', to: 'dist/yyy.ext' }
  ]
)

New syntax:

new CopyWebpackPlugin(
  { 
    patterns: [
      { from: 'src/xxx.ext', to: 'dist/xxx.ext' },
      { from: 'src/yyy.ext', to: 'dist/yyy.ext' }
    ]
  }
)

This is related to #2595.

**Comment by mattgodbolt** [comment]
Closing in favour of #2595. And we probably need to update our `npm` version.
