### ISSUE TITLE
[BUG] SyntaxError in json from demangler

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2984]
Seen in logs:

```
Sep 30 14:51:24 ip-172-30-1-175 amazon  error: Error with stdin stream: write EPIPE {"errno":"EPIPE","code":"EPIPE","syscall":"write","stack":"Error: write EPIPE\n    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)\n    at WriteWrap.callbackTrampoline (internal/async_hooks.js:120:14)"} 
Sep 30 14:51:24 ip-172-30-1-175 amazon warn: Caught exception SyntaxError: Unexpected token  
Sep 30 14:51:24 ip-172-30-1-175 amazon      in JSON at position 1048576 during opt demangle parsing 
```

no further info ( https://my.papertrailapp.com/groups/1243314/events?q=-POST+-GET+-Sandbox&focus=1380321377508937728&selected=1380321377508937728 for those with access)

**Comment by jeremy-rifkin** [comment]
Looks like the error is still around, it has happened once in the last week
```
Jun 12 16:13:06Z ip amazon
error: Error with stdin stream: write EPIPE 

{
  "code": "EPIPE",
  "errno": -32,
  "stack": "Error: write EPIPE\n at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)\n at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)",
  "syscall": "write"
}

Jun 12 16:13:06Z ip amazon warn: Caught exception SyntaxError: Unexpected token T in JSON at position 1048578 during opt demangle parsing
```

**Comment by jeremy-rifkin** [comment]
I just realized `at position 1048576` is 1024 * 1024 which is our default maxOutput. I'm not sure how there could be 1MB of symbols worth of demangling to do, but, maybe we should up the limit? At the very least we can give a better diagnostic if the result is truncated.
