### ISSUE TITLE
[BUG] Newest NodeJS release (non-LTS) fails with Windows 10 19044.1237

### ISSUE THREAD

**Issue by jackson2k2** [compiler-explorer/compiler-explorer#3047]
This is after following the instructions as exactly stated (the only difference was that I had to force npm to update webpack).

```
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\webpack\lib\NormalModule.js:471:10)
    at G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\webpack\lib\NormalModule.js:503:5
    at G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\webpack\lib\NormalModule.js:358:12
    at G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.loader (G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\source-map-loader\dist\index.js:37:5)
    at LOADER_EXECUTION (G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at G:\Programs\Reverse Engineering\Compiler Explorer\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
This is using the latest repository, and I will admit that I am using this on a WinBtrfs drive-- I have not yet tested to see if this problem is on a supported filesystem, but the issue looks to be something else; probably OpenSSL.

**Comment by partouf** [comment]
Can you tell us what exact Node.js version you installed?

**Comment by partouf** [comment]
> 17.0.1 current. This appears to be mostly a webpack issue with legacy hash algorithms, so complaints are probably better off redirected to there: https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported

I appreciate the comments, but until we actually support this nodejs version and the package upgrades that they come with, I would suggest downgrading nodejs to latest 14 if you want to run compiler-explorer locally.
