### ISSUE TITLE
[BUG]: Embedded IFrames are BROKEN

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#3397]
### Describe the bug

```
helpers.ts:120 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at t.getUi (settings.ts:161:30)
    at t.updateDisplay (settings.ts:165:47)
    at t.putUi (settings.ts:157:14)
    at e.onSettingsChange (settings.ts:239:21)
    at e.setSettings (settings.ts:225:14)
    at new e (settings.ts:216:14)
    at main.js:106:26
    at HTMLDocument.<anonymous> (main.js:520:20)
    at h (jquery.js:3766:29)
    at c (jquery.js:3834:12)
    at o (helpers.ts:98:17)
```

### Steps to reproduce

embed

### Expected behavior

should work

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by RubenRBS** [comment]
From the val() function that is responsible for this:
```ts
 protected val(): string | number | string[] {
    //  If it's undefined, something went wrong, so the following exception is helpful
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    return this.elem.val()!;
}
```
so, thanks past Me, I guess
