### ISSUE TITLE
[BUG]: Internal Compiler Explorer error: TypeError: Cannot set properties of undefined (setting 'name') for MSVC compilers

### ISSUE THREAD

**Issue by AMS21** [compiler-explorer/compiler-explorer#3412]
### Describe the bug

No assembly output for the MSVC compiler. Instead we get:
```
Internal Compiler Explorer error: TypeError: Cannot set properties of undefined (setting 'name')
    at Win32VcCompiler.findLibVersion (C:\compiler-explorer\lib\base-compiler.js:461:21)
    at C:\compiler-explorer\lib\base-compiler.js:634:39
    at Proxy.map (C:\compiler-explorer\node_modules\underscore\modules\map.js:13:22)
    at Win32VcCompiler.getIncludeArguments (C:\compiler-explorer\lib\base-compiler.js:633:28)
    at Win32VcCompiler.prepareArguments (C:\compiler-explorer\lib\compilers\win32.js:96:34)
    at Win32VcCompiler.doCompilation (C:\compiler-explorer\lib\base-compiler.js:1245:18)
    at C:\compiler-explorer\lib\base-compiler.js:1650:52
    at async run (C:\compiler-explorer\node_modules\p-queue\dist\index.js:163:29)
Compiler returned: -1
```

Tested with
- Mozilla Firefox 97.0.1
- Chromium 98.0.4758.102 Arch Linux

### Steps to reproduce

1. Visit https://godbolt.org/z/hGb7Wh1zf
2. See the error in the output window for windows

### Expected behavior

No internal compiler explorer error.

### Reproduction link

https://godbolt.org/z/hGb7Wh1zf

### Screenshots

Not applicable

### Operating System

Linux 5.16.11-2-MANJARO x86_64

### Browser version

Mozilla Firefox 97.0.1

**Comment by dcleland** [comment]
Fails for all variants of the MSVC compilers (x64, x86 and arm64)

Tested with

Vivalid 5.1.2567.73 (Stable channel) (64-bit)
Windows 10 Version 21H2

**Comment by partouf** [comment]
this should be fixed now
