### ISSUE TITLE
[BUG]: GHC Core and Cmm views won't open

### ISSUE THREAD

**Issue by MattX** [compiler-explorer/compiler-explorer#3951]
### Describe the bug

In Haskell mode, I'm able to open the assembly and Haskell STG views, but not Core or Cmm.

I get an error in the console when trying to do it:

```
Uncaught ReferenceError: $ is not defined
    at t.getInitialHTML (haskellcmm-view.ts:46:9)
    at t.e (pane.ts:69:32)
    at t [as constructor] (pane.ts:260:9)
    at new t (haskellcmm-view.ts:39:9)
    at e.haskellCmmViewFactory (hub.ts:509:16)
    at new <anonymous> (hub.ts:127:82)
    at new s.items.Component (goldenlayout.js:3706:18)
    at s.LayoutManager.createContentItem (goldenlayout.js:828:17)
    at s.items.Stack._createContentItems (goldenlayout.js:3599:38)
    at s.items.AbstractContentItem (goldenlayout.js:3104:8)
    at new s.items.Stack (goldenlayout.js:4381:31)
    at s.LayoutManager.createContentItem (goldenlayout.js:828:17)
    at s.LayoutManager._$normalizeContentItem (goldenlayout.js:1131:30)
    at s.items.RowOrColumn.addChild (goldenlayout.js:3885:36)
    at D.<anonymous> (compiler.js:588:25)
    at Je (underscore-umd-min.js:6:7254)
    at HTMLButtonElement.<anonymous> (underscore-umd-min.js:6:7682)
    at HTMLButtonElement.<anonymous> (underscore-umd-min.js:6:782)
    at HTMLButtonElement.dispatch (jquery.js:5430:27)
    at m.handle (jquery.js:5234:28)
    at HTMLButtonElement.o (helpers.ts:99:17)
```

### Steps to reproduce

1. Visit goldbolt
2. Select Haskell
3. In the compiler pane, select Add new... > GHC Core

### Expected behavior

A new panel opens with GHC Core view.

### Screenshots

Not applicable

### Operating System

MacOS 12.5

### Browser version

Version 103.0.5060.134

**Comment by partouf** [comment]
@matsjla I think you broke something

**Comment by matsjla** [comment]
Damn it, I thought I had all of them...

**Comment by partouf** [comment]
Fix is now live, thanks for the report @MattX
