### ISSUE TITLE
[BUG]: Loop dump without preceding dump

### ISSUE THREAD

**Issue by tavianator** [compiler-explorer/compiler-explorer#4195]
### Describe the bug

The LLVM opt pipeline viewer gives this error:

```
<An error occurred while generating the optimization pipeline output: Assertion error in llvm-print-after-all-parser: Loop dump without preceding dump
Error: Assertion Error
    at assert (/infra/.deploy/lib/parsers/llvm-pass-dump-parser.js:32:23)
    at LlvmPassDumpParser.breakdownIntoPassDumpsByFunction (/infra/.deploy/lib/parsers/llvm-pass-dump-parser.js:258:17)
    at LlvmPassDumpParser.breakdownOutput (/infra/.deploy/lib/parsers/llvm-pass-dump-parser.js:412:46)
    at LlvmPassDumpParser.process (/infra/.deploy/lib/parsers/llvm-pass-dump-parser.js:452:21)
    at RustCompiler.processLLVMOptPipeline (/infra/.deploy/lib/base-compiler.js:884:40)
    at RustCompiler.generateLLVMOptPipeline (/infra/.deploy/lib/base-compiler.js:859:48)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 4)
    at async RustCompiler.doCompilation (/infra/.deploy/lib/base-compiler.js:1383:132)>
```

### Steps to reproduce

Go to the reproducer link

### Expected behavior

Should see the opt pipeline view

### Reproduction link

https://rust.godbolt.org/z/3eWad3WWh

### Operating System

Arch Linux

### Browser version

Mozilla Firefox 106.0.1

**Comment by partouf** [comment]
Thanks for the example.
We'll have to investigate what dump this produces and then why this is triggered https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/parsers/llvm-pass-dump-parser.ts#L291

**Comment by jeremy-rifkin** [comment]
I'm able to reproduce this locally. It looks like the issue is there is a
```IR Dump Before LoopInstSimplifyPass on Loop at depth 1 containing: %bb3<header>,%bb2.i,%bb4.i<exiting>,%"_ZN7example12Vec$LT$T$GT$8as_slice17hb481700be3fe636aE.exit.i.i.i",%"_ZN7example12Vec$LT$T$GT$8as_slice17hb481700be3fe636aE.exit6.i.i.i",%bb4.i.i.i<exiting>,%bb6.i<exiting>,%"_ZN54_$LT$example..Name$u20$as$u20$core..cmp..PartialEq$GT$2eq17h0bee713df8f622beE.exit",%bb1.backedge<latch><exiting>```
which contains only loop code, following a
```IR Dump After SimpleLoopUnswitchPass on Loop at depth 1 containing: %bb3<header>,%bb2.i,%bb4.i<exiting>,%"_ZN7example12Vec$LT$T$GT$8as_slice17hb481700be3fe636aE.exit.i.i.i"<exiting>,%"_ZN7example12Vec$LT$T$GT$8as_slice17hb481700be3fe636aE.exit6.i.i.i",%bb4.i.i.i<exiting>,%bb6.i<exiting>,%"_ZN54_$LT$example..Name$u20$as$u20$core..cmp..PartialEq$GT$2eq17h0bee713df8f622beE.exit",%bb1.backedge<latch><exiting> (invalidated)```
Which dumps everything.

At the moment loop dumps are matched to their corresponding functions by looking at what function was being dumped previously.

**Comment by jeremy-rifkin** [comment]
Here's a more minimal repro https://godbolt.org/z/1WbGY8Gfq
