### ISSUE TITLE
[BUG]: Scala support is broken

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4681]
### Describe the bug

https://godbolt.org/z/3Erb54WPn

### Steps to reproduce

```
Internal Compiler Explorer error: Error: Unwrap failed, at lib/compilers/java.js:341 `firstSourceLine: methods.reduce((p, m) => (p === -1 ? unwrap(m.startLine) : Math.min(p, unwrap(m.startLine))), -1),`
    at fail (/infra/.deploy/lib/assert.js:78:15)
    at unwrap (/infra/.deploy/lib/assert.js:91:9)
    at /infra/.deploy/lib/compilers/java.js:341:67
    at Array.reduce (<anonymous>)
    at ScalaCompiler.parseAsmForClass (/infra/.deploy/lib/compilers/java.js:341:38)
    at /infra/.deploy/lib/compilers/java.js:210:52
    at Array.map (<anonymous>)
    at ScalaCompiler.processAsm (/infra/.deploy/lib/compilers/java.js:210:36)
    at ScalaCompiler.afterCompilation (/infra/.deploy/lib/base-compiler.js:1861:38)
    at runMicrotasks (<anonymous>)
Compiler returned: -1
```

### Expected behavior

working :)

### Reproduction link

https://godbolt.org/z/3Erb54WPn

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Fixed by #4683
