### ISSUE TITLE
[BUG]: The "path" argument must be of type string. Received type number (1)

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#5183]
### Describe the bug

Since update we get tthis error:
```
Internal Compiler Explorer error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number (1)
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:1172:7)
    at ClangCompiler.getOutputFilename (file:///infra/.deploy/lib/base-compiler.js:1154:25)
    at ClangCompiler.getCompilationInfo (file:///infra/.deploy/lib/base-compiler.js:1559:34)
    at ClangCompiler.afterCompilation (file:///infra/.deploy/lib/compilers/clang.js:97:38)
    at file:///infra/.deploy/lib/base-compiler.js:2063:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///infra/.deploy/lib/base-compiler.js:2044:25
    at async file:///infra/.deploy/node_modules/p-timeout/index.js:90:13
Compiler returned: -1
```

### Steps to reproduce

1. visit https://godbolt.org/z/KPe331GKj
2. force recompile

### Expected behavior

no error!

### Reproduction link

https://godbolt.org/z/KPe331GKj

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
Seems unrelated to the short link and just a "force recompile" issue. Maybe related to #5111 ?
