### ISSUE TITLE
Error opening output pane

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#5552]
I'm unable to open the output pane for the following url https://godbolt.org/z/aoW4odGEP. The following errors are in the console:

```
Uncaught TypeError: n is undefined
    addOutputLines output.ts:176
    onCompileResult output.ts:209
    emit goldenlayout.js:255
    emit event-hub.ts:70
    resendResult compiler.ts:3269
    onOutputOpened compiler.ts:2023
    emit goldenlayout.js:255
    emit event-hub.ts:70
    t output.ts:80
    outputFactory hub.ts:414
    e hub.ts:125
    Component goldenlayout.js:3706
    createContentItem goldenlayout.js:828
    _$normalizeContentItem goldenlayout.js:1131
    _onDragStart goldenlayout.js:2286
    emit goldenlayout.js:255
    _startDrag goldenlayout.js:431
    onMouseMove goldenlayout.js:400
    jQuery 2
    n helpers.ts:98
    kn trycatch.ts:234
    yt instrument.ts:595
    jQuery 6
    onMouseDown goldenlayout.js:378
    jQuery 2
    n helpers.ts:98
output.ts:176:26
```

```
Uncaught TypeError: Cannot read properties of undefined (reading 'concat')
    at t.addOutputLines (output.ts:176:34)
    at t.onCompileResult (output.ts:209:18)
    at r.utils.EventHub.emit (goldenlayout.js:255:30)
    at e.emit (event-hub.ts:70:37)
    at t.resendResult (compiler.ts:3269:31)
    at t.onOutputOpened (compiler.ts:2023:18)
    at r.utils.EventHub.emit (goldenlayout.js:255:30)
    at e.emit (event-hub.ts:70:37)
    at new t (output.ts:80:23)
    at e.outputFactory (hub.ts:414:16)
    at new <anonymous> (hub.ts:125:72)
    at new r.items.Component (goldenlayout.js:3706:18)
    at r.LayoutManager.createContentItem (goldenlayout.js:828:17)
    at r.LayoutManager._$normalizeContentItem (goldenlayout.js:1131:30)
    at r.controls.DragSource._onDragStart (goldenlayout.js:2286:41)
    at r.utils.DragListener.emit (goldenlayout.js:255:30)
    at r.utils.DragListener._startDrag (goldenlayout.js:431:8)
    at r.utils.DragListener.onMouseMove (goldenlayout.js:400:11)
    at HTMLDocument.dispatch (jquery.js:5145:27)
    at m.handle (jquery.js:4949:28)
    at HTMLDocument.n (helpers.ts:98:17)
```

**Comment by jehuamanna** [comment]
@jeremy-rifkin is this issue still persisting? I am unable to produce.
