### ISSUE TITLE
[BUG]: CFG generation broken with opt tool

### ISSUE THREAD

**Issue by SUPERCILEX** [compiler-explorer/compiler-explorer#6014]
### Describe the bug

```
Internal Compiler Explorer error: Error: Not implemented
    at LlvmIrInstructionSetInfo.isJmpInstruction (file:///infra/.deploy/lib/cfg/instruction-sets/llvm-ir.js:30:15)
    at ClangCFGParser.splitToBasicBlocks (file:///infra/.deploy/lib/cfg/cfg-parsers/base.js:81:46)
    at ClangCFGParser.generateFunctionCfg (file:///infra/.deploy/lib/cfg/cfg-parsers/base.js:245:34)
    at Module.generateStructure (file:///infra/.deploy/lib/cfg/cfg.js:50:53)
    at OptCompiler.afterCompilation (file:///infra/.deploy/lib/base-compiler.js:2227:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///infra/.deploy/lib/base-compiler.js:2177:24
    at async env.enqueue.abandonIfStale (file:///infra/.deploy/lib/base-compiler.js:2158:25)
    at async file:///infra/.deploy/node_modules/p-timeout/index.js:99:13
Compiler returned: -1
```

### Steps to reproduce

See repro link

### Expected behavior

Don't crash.

### Reproduction link

https://godbolt.org/z/bYYYP4zn8

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Thanks for the bug report, that's odd
