### ISSUE TITLE
Android kotlin/java compilers fail to compile

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#6015]
Currently compilation fails with an ICEE
```
Internal Compiler Explorer error: TypeError: Cannot read properties of undefined (reading 'split')
    at Dex2OatCompiler.parseAsm (file:///infra/.deploy/lib/compilers/dex2oat.js:241:36)
    at Dex2OatCompiler.processAsm (file:///infra/.deploy/lib/compilers/dex2oat.js:189:109)
    at Dex2OatCompiler.afterCompilation (file:///infra/.deploy/lib/base-compiler.js:2207:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///infra/.deploy/lib/base-compiler.js:2177:24
    at async env.enqueue.abandonIfStale (file:///infra/.deploy/lib/base-compiler.js:2158:25)
    at async file:///infra/.deploy/node_modules/p-timeout/index.js:99:13
Compiler returned: -1
```

**Comment by kevinjeon-g** [comment]
Hi, thanks for the heads up! I believe this error should be resolved with https://github.com/compiler-explorer/compiler-explorer/pull/6011

**Comment by jeremy-rifkin** [comment]
Thanks!

**Comment by partouf** [comment]
can't really exactly remember how this was fixed, but it does appear to be fixed
