### ISSUE TITLE
[BUG]: Error when opening a zip project file in IDE mode

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#6019]
### Describe the bug

```
multifile-service.ts:110 Uncaught (in promise) TypeError: l.filter is not a function
    at e.getLanguageIdFromFilename (multifile-service.ts:110:40)
    at e.<anonymous> (multifile-service.ts:164:34)
    at tslib.es6.mjs:147:21
    at Object.next (tslib.es6.mjs:128:51)
    at r (tslib.es6.mjs:118:56)
```

cc @OfekShilon 
needs to be reverted to underscore, languages is an object

### Steps to reproduce

-

### Expected behavior

-

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
Sorry, my bad.
