### ISSUE TITLE
[BUG]: F# Compiler fails, complains of 'read only file system'.

### ISSUE THREAD

**Issue by robertmaxton42** [compiler-explorer/compiler-explorer#6069]
### Describe the bug

Possible duplicate of #4675, but I can't get the exact same error message to show up anymore, so I'm making a new issue. (I think I saw it once while playing with the compiler configuration, though?)

Regardless, the sample program doesn't compile.  Specifically, I get

```
System.IO.IOException: Read-only file system : '/nosym'
   at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateDirectory(String path)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

### Steps to reproduce

1. Visit godbolt.org
2. Select `F#`
3. Note the error in the output pane

### Expected behavior

Program compiles and runs

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
We've rolled out a tactical fix for the `/nosym` but now:
```
An issue was encountered verifying workloads. For more information, run "dotnet workload update".
/opt/compiler-explorer/dotnet-trunk-20240131/.dotnet/sdk/9.0.100-alpha.1.23615.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1064: Package FSharp.Core, version 8.0.200-beta.23613.4 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions. [/app/CompilerExplorer.fsproj]
Compiler returned: 1
```

I don't know what that means in this context, or if that was an issue before

**Comment by partouf** [comment]
> We've rolled out a tactical fix for the `/nosym` but now:
> 
> ```
> An issue was encountered verifying workloads. For more information, run "dotnet workload update".
> /opt/compiler-explorer/dotnet-trunk-20240131/.dotnet/sdk/9.0.100-alpha.1.23615.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1064: Package FSharp.Core, version 8.0.200-beta.23613.4 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions. [/app/CompilerExplorer.fsproj]
> Compiler returned: 1
> ```
> 
> I don't know what that means in this context, or if that was an issue before

That was the issue before yes, and was not fixed yet. But C# now works again

**Comment by partouf** [comment]
this should be really resolved now
