### ISSUE TITLE
[BUG]: 'Detailed Compiler Flags' popup doesn't work

### ISSUE THREAD

**Issue by virtuald** [compiler-explorer/compiler-explorer#6088]
### Describe the bug

'Detailed Compiler Flags' popup doesn't work. In developer tools on Chrome I see the following error when I click it:

```
helpers.ts:122 Uncaught TypeError: Cannot read properties of undefined (reading 'updateOptions')
    at t.apply (fontscale.ts:124:52)
    at new t (fontscale.ts:113:14)
    at t.registerButtons (pane.ts:297:26)
    at t.e (pane.ts:87:14)
    at t [as constructor] (pane.ts:288:14)
    at new t (flags-view.ts:44:14)
    at e.flagsViewFactory (hub.ts:450:16)
    at new <anonymous> (hub.ts:132:76)
    at new r.items.Component (goldenlayout.js:3706:18)
    at r.LayoutManager.createContentItem (goldenlayout.js:828:17)
    at r.items.Stack._createContentItems (goldenlayout.js:3599:38)
    at r.items.AbstractContentItem (goldenlayout.js:3104:8)
    at new r.items.Stack (goldenlayout.js:4381:31)
    at r.LayoutManager.createContentItem (goldenlayout.js:828:17)
    at r.LayoutManager._$normalizeContentItem (goldenlayout.js:1131:30)
    at r.items.RowOrColumn.addChild (goldenlayout.js:3885:36)
    at HTMLButtonElement.<anonymous> (compiler.ts:741:29)
    at HTMLButtonElement.dispatch (jquery.js:5145:27)
    at m.handle (jquery.js:4949:28)
    at HTMLButtonElement.n (helpers.ts:100:17)
```

### Steps to reproduce

Visit godbolt, select "Detailed Compiler Flags" in the dropdown, watch nothing happen.

### Expected behavior

Something happened.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
Thanks very much for the bugreport!

The fix is now live
