### ISSUE TITLE
[BUG]: Certain {fmt} versions broken in certain Clangs

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#6249]
### Describe the bug

[BUG]: Certain {fmt} versions broken in certain Clangs

### Steps to reproduce

- Set compiler to x86-64 Clang 16.0.0; or to 18.1.0 with -stdlib=libc++
- Libraries / add {fmt} 7.0.0 or 6.2.1
- Don't worry what the input code is, it doesn't matter

### Expected behavior

```
square(int):                             # @square(int)
        push    rbp
        mov     rbp, rsp
        mov     dword ptr [rbp - 4], edi
        mov     eax, dword ptr [rbp - 4]
        imul    eax, dword ptr [rbp - 4]
        pop     rbp
        ret
```

### Actual behavior
```
Internal Compiler Explorer error: Error: undefined is not a valid uri or options object.
    at request (/infra/.deploy/node_modules/request/index.js:44:11)
    at file:///infra/.deploy/lib/buildenvsetup/ceconan.js:162:25
    at new Promise (<anonymous>)
    at BuildEnvSetupCeConanDirect.downloadAndExtractPackage (file:///infra/.deploy/lib/buildenvsetup/ceconan.js:99:16)
    at file:///infra/.deploy/lib/buildenvsetup/ceconan.js:233:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async ClangCompiler.doCompilation (file:///infra/.deploy/lib/base-compiler.js:1751:27)
    at async file:///infra/.deploy/lib/base-compiler.js:2204:63
    at async env.enqueue.abandonIfStale (file:///infra/.deploy/lib/base-compiler.js:2186:25)
Compiler returned: -1
```

### Reproduction link

https://godbolt.org/z/9nrnvvWqc

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
Fixed after restarting conan by @partouf

**Comment by partouf** [comment]
Conan crashed again, restarted

**Comment by partouf** [comment]
correction, the server is out of diskspace again, so not alive just yet
