### ISSUE TITLE
[BUG]: Integration of solc 

### ISSUE THREAD

**Issue by sayon** [compiler-explorer/compiler-explorer#6967]
### Describe the bug

Error:
```
Internal Compiler Explorer error: TypeError: Cannot read properties of undefined (reading '.code')
    at file:///infra/.deploy/lib/compilers/solidity.js:82:70
    at Array.sort (<anonymous>)
    at SolidityCompiler.processAsm (file:///infra/.deploy/lib/compilers/solidity.js:82:18)
    at SolidityCompiler.afterCompilation (file:///infra/.deploy/lib/base-compiler.js:2164:44)
    at async file:///infra/.deploy/lib/base-compiler.js:2134:24
    at async env.enqueue.abandonIfStale (file:///infra/.deploy/lib/base-compiler.js:2115:25)
    at async file:///infra/.deploy/node_modules/p-timeout/index.js:99:13
Compiler returned: -1 
```

### Steps to reproduce

1. Select the compiler: `solc 0.8.21`  
2. Input the following program:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.16;

interface IExternalContract { 
    function h(uint256) external returns (uint256) ; 
}

contract GasChecker {
    IExternalContract C;

    constructor(address _externalContractAddress) {
        C = IExternalContract(_externalContractAddress);
    }

    function checkGasAndCall() external {

        uint256 start = gasleft();
        uint256 x = C.h(0);
        uint256 end = gasleft();

        C.h(x+end+start);
    }
}

```

### Expected behavior

Correct compilation followed by displaying the assembly code.

### Reproduction link

 https://godbolt.org/z/9v8MxGK68

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
Thank you very much for reporting! You should see the fix at the next deploy.
